### ISSUE TITLE
No Issue just a new mod idea 

### ISSUE THREAD

**Issue by Saptexx** [UnclaimedBloom6/IllegalMap#11]
hey this is not an issue or bug report but i don't know how else to reach you. So my question/ idea is that you make a module similar to dmap that hollows in the crystal and scans all the block so you get waypoints or coordinates where all even loactions like king, queen are.

**Comment by UnclaimedBloom6** [comment]
I'm not interested in the crystal hollows, but I'm pretty sure other mods like pizza or shady (?) have scanners for that.
