### ISSUE TITLE
IllegalMap goes black mid-run

### ISSUE THREAD

**Issue by dead-soull** [UnclaimedBloom6/IllegalMap#13]
When it goes black fps goes to near 0 values, and I didn't find a solution to fix it mid-run except restarting your client completely

**Comment by preindex** [comment]
I also have this issue. It only happens on one laptop for me.

Crashing Laptop Specs:
AMD Ryzen 7 5800H
16 GB RAM
NVIDIA GeForce RTX 3060 Laptop GPU

NOT Crashing Laptop Specs:
i9 11980HK
32 GB RAM
NVIDIA GeForce RTX 3080 Laptop GPU
